In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model

In [73]:
url = "http://bit.ly/w-data "
df= pd.read_csv(url)
print(df)

    Hours  Scores
0     2.5      21
1     5.1      47
2     3.2      27
3     8.5      75
4     3.5      30
5     1.5      20
6     9.2      88
7     5.5      60
8     8.3      81
9     2.7      25
10    7.7      85
11    5.9      62
12    4.5      41
13    3.3      42
14    1.1      17
15    8.9      95
16    2.5      30
17    1.9      24
18    6.1      67
19    7.4      69
20    2.7      30
21    4.8      54
22    3.8      35
23    6.9      76
24    7.8      86


In [58]:
X = df[['Hours']]
y = df[['Scores']]

In [59]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.2, random_state = 0)

In [60]:
from sklearn.linear_model import LinearRegression
lrs = LinearRegression()
lrs.fit(X_train, y_train)

LinearRegression()

In [61]:
print(X_test)

    Hours
5     1.5
2     3.2
19    7.4
16    2.5
11    5.9


In [70]:
lrs.predict(y_test)
lrs.predict([[9.5]])

array([[96.48038327]])

In [49]:
lrs.score(X_test, y_test)

0.9439531546768674

In [50]:
print(y_test)

    Scores
5       20
2       27
19      69
16      30
11      62


In [66]:
s = df['Scores']

In [71]:
lrs.predict([[9.5]])

array([[96.48038327]])

In [72]:
lrs.predict([[5.5]])

array([[56.63964781]])